export const BLOGITEMS = 'BLOG_ITEMS'
export const ADDTOCARD = 'ADD_TO_CARD'
export const HANDLINGFILTERS = 'HANDLING_FILTERS'
export const REMOVEITEMARR = 'REMOVE_ITEM_FROM_ARR'
export const OPENDROPDOWN = 'OPEN_DROPDOWN'

export const GETMEALSFILTER = 'GET_MEALS_FILTER'
export const GETMEALS = 'GET_MEALS'
export const RESETMEALS = 'RESET_MEALS'

export const GETFILTERS = 'GET_FILTERS'

export const SIGNUPUSER = 'SIGNUP_USER'
export const SIGNINUSER = 'SIGNIN_USER'
export const DELETEUSER = 'DELETE_USER'

export const VERIFYUSER = 'VERIFY_USER'
export const VERIFYREFRESH = 'VERIFY_REFRESH'
export const GETUSER = 'GET_USER'
export const LOGOUTCALL = 'LOGOUT_CALL'

export const GETTESTIMONIALS = 'GET_TESTIMONIALS'
export const POSTTESTIMONIALS = 'POST_TESTIMONIALS'

export const FORGETPASSWORD = 'FORGET_PASSWORD'
export const CHANGEPASSWORD = 'CHANGE_PASSWORD'

export const ERROR = 'ERROR'